### ISSUE TITLE
Should `Content-Encoding` be cached?

### ISSUE THREAD

**Issue by kblcuk** [addisonj/node-cacher#27]
Greetings!

I have an Express app which uses [compression](https://github.com/expressjs/compression) and Cacher.

Since Cacher caches all headers including `Content-Encoding`, all the subsequent (cached) requests receive non-compressed version of response due to the way `compress` hooks into response object.

So I wonder whether that header should be cached at all? Currently Cacher might end up "telling" client that content is encoded (whereas it is not) and vice versa (causing for instance Chrome to fail loading page since it fails to decode content that is not compressed).

Thanks in advance!

**Comment by kblcuk** [comment]
I have a very basic test setup in case you need it:

```
var express = require('express');
var compression = require('compression');
var Cacher = require("cacher");
// use the default in memory cache
var cacher = new Cacher();
var app = express();

var cacher = new Cacher();

app.use(cacher.cache('seconds', 20));
app.use(compression());

app.get('/', function (req, res) {
  var twoKOfData = randomString(2048);
  res.send(twoKOfData);
});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);
});


var randomString = function(length) {
  var text = "";
  var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for(var i = 0; i < length; i++) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
}
```

Try doing `curl -v --raw -H "Accept-Encoding:gzip" http://localhost:3000/` and then `curl -v --raw http://localhost:3000/`.

**Comment by AndrewBarba** [comment]
+1 I am experiencing the exact same issue

**Comment by addisonj** [comment]
Sorry for the delay... this is a very good point. This isn't so much an issue with the response headers being cached (which we do want to cache to have a proper response) but with the function used to generate the cache key. In some sense the `Accept-Encoding` (and `Accepts` header) are requests for different resources whereas the current implementation of how we generate the key to cache 

The default implementation is really stupid: 

```
Cacher.prototype.genCacheKey = function(req) {
  return req.originalUrl
}
```

if you were to some more smart like:

```
cacher.genCacheKey = function(req) {
  return req.originalUrl + req.header('accepts') + req.header('accept-encoding')
}
```

Then you would not get the two requests mixed up. Initially, the plan was to keep the genCacheKey function pretty generic and get most people to override it... since I didn't feel like I was smart enough to come up with a good default implementation, but this might be confusing...

Try something like that out and see if that fixes your issue and perhaps come up with a better default implementation.

**Comment by frank-dspeed** [comment]
close this issu as its solved !

**Comment by kblcuk** [comment]
Most likely this has been solved one way or another, or if this is still the case -- I'd suppose that it's something else than what caused this 6 years ago 😅 
Closing.
